name: build

on:
  pull_request:
    types: [ labeled ]

jobs:
  bump-version:
    if: ${{ github.event.label.name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          echo "new tag: v$new_tag"
          ## update python version
          echo "version = 'v$new_tag'" > 'vault/version.py'
          git commit --reuse-message=HEAD@{1} vault/version.py || echo "No changes to commit"
          git push origin
          git tag v$new_tag
          git push origin v$new_tag
